import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  adaptLegacyCase,
  sha256Hex
} from '../../../src/can-lam-sang/adapters/legacy-case-adapter.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../..');
const bankPath = resolve(repoRoot, 'public/tu-chan/index.html');
const defaultOutput = resolve(repoRoot, 'build/can-lam-sang/cls-seed.sql');
const outputPath = process.argv[2] ? resolve(process.argv[2]) : defaultOutput;

function sqlText(value) {
  return "'" + String(value).replaceAll("'", "''") + "'";
}

function sqlNullableText(value) {
  return value == null ? 'null' : sqlText(value);
}

function sqlDate(value) {
  return value == null ? 'null' : sqlText(value) + '::date';
}

function sqlTextArray(values) {
  const items = Array.isArray(values) ? values : [];
  if (items.length === 0) return "'{}'::text[]";
  return 'array[' + items.map(sqlText).join(', ') + ']::text[]';
}

function jsonbLiteral(value) {
  return sqlText(JSON.stringify(value)) + '::jsonb';
}

function resourceContent(resource) {
  return JSON.stringify(resource);
}

const html = await readFile(bankPath, 'utf8');
const match = html.match(/id="bank-data">([\s\S]*?)<\/script>/);
if (!match) throw new Error('legacy bank-data missing');

const bank = JSON.parse(match[1]);
if (bank.length !== 156) {
  throw new Error(`expected 156 legacy cases, got ${bank.length}`);
}

const adapted = bank.map(adaptLegacyCase);

/*
 * Legacy resource IDs are not guaranteed globally unique: the same legacy ID
 * can appear with different unverified metadata in different cases.
 * Never merge those variants silently. If a base ID collides, derive a stable
 * ID from the exact resource JSON hash and use the same derived ID inside the
 * seeded server-only answer key and the resources registry.
 */
const variantsByBaseId = new Map();
for (const { answer_key } of adapted) {
  for (const resource of answer_key.resources_after_submission || []) {
    const baseId = resource.resource_id;
    const content = resourceContent(resource);
    if (!variantsByBaseId.has(baseId)) variantsByBaseId.set(baseId, new Map());
    variantsByBaseId.get(baseId).set(content, resource);
  }
}

const resourceIdByContent = new Map();
const resourceMap = new Map();
let resourceIdCollisions = 0;

for (const [baseId, variants] of variantsByBaseId) {
  const entries = [...variants.entries()].sort(([a], [b]) => a.localeCompare(b));
  if (entries.length > 1) resourceIdCollisions += 1;

  for (const [content, resource] of entries) {
    const resourceId = entries.length === 1
      ? baseId
      : `${baseId}-${sha256Hex(content).slice(0, 12)}`;
    const normalized = { ...resource, resource_id: resourceId };
    const key = baseId + '\u001f' + content;
    resourceIdByContent.set(key, resourceId);
    resourceMap.set(resourceId, normalized);
  }
}

const normalized = adapted.map(({ public_bundle, answer_key }) => {
  const resources = (answer_key.resources_after_submission || []).map(resource => {
    const content = resourceContent(resource);
    const key = resource.resource_id + '\u001f' + content;
    const resourceId = resourceIdByContent.get(key);
    if (!resourceId) {
      throw new Error(`resource normalization missing: ${resource.resource_id}`);
    }
    return { ...resource, resource_id: resourceId };
  });

  return {
    public_bundle,
    answer_key: {
      ...answer_key,
      resources_after_submission: resources
    }
  };
});

const lines = [
  'begin;',
  '',
  '-- Generated by 004_cls_seed_generator.mjs. Do not commit generated output.',
  '-- Feature flag is always seeded disabled.',
  '-- Legacy resource-ID collisions are deterministically disambiguated by content hash.',
  "insert into can_lam_sang_private.feature_flags (flag_key, enabled, allowlist_user_ids)",
  "values ('clinical_lab_room_v1', false, '{}'::uuid[])",
  'on conflict (flag_key) do update',
  "set enabled = false, allowlist_user_ids = '{}'::uuid[];",
  ''
];

for (const { public_bundle } of normalized) {
  const content = JSON.stringify(public_bundle);
  lines.push(
    'insert into can_lam_sang_private.case_bundles',
    '  (case_id, schema_version, data_origin, review_status, public_bundle, content_sha256)',
    'values (',
    `  ${sqlText(public_bundle.case_id)},`,
    `  ${sqlText(public_bundle.schema_version)},`,
    `  ${sqlText(public_bundle.data_origin)},`,
    `  ${sqlText(public_bundle.review_status)},`,
    `  ${jsonbLiteral(public_bundle)},`,
    `  ${sqlText(sha256Hex(content))}`,
    ')',
    'on conflict (case_id) do update set',
    '  schema_version = excluded.schema_version,',
    '  data_origin = excluded.data_origin,',
    '  review_status = excluded.review_status,',
    '  public_bundle = excluded.public_bundle,',
    '  content_sha256 = excluded.content_sha256;',
    ''
  );
}

for (const { answer_key } of normalized) {
  const content = JSON.stringify(answer_key);
  lines.push(
    'insert into can_lam_sang_private.answer_keys',
    '  (case_id, answer_key, content_sha256)',
    'values (',
    `  ${sqlText(answer_key.case_id)},`,
    `  ${jsonbLiteral(answer_key)},`,
    `  ${sqlText(sha256Hex(content))}`,
    ')',
    'on conflict (case_id) do update set',
    '  answer_key = excluded.answer_key,',
    '  content_sha256 = excluded.content_sha256;',
    ''
  );
}

for (const resource of [...resourceMap.values()].sort((a, b) =>
  a.resource_id.localeCompare(b.resource_id)
)) {
  lines.push(
    'insert into can_lam_sang_private.resources (',
    '  resource_id, schema_version, resource_type, source, title,',
    '  organization, year_version, citation, checked_date, reviewer,',
    '  review_status, license, provenance_tags',
    ') values (',
    `  ${sqlText(resource.resource_id)},`,
    `  ${sqlText(resource.schema_version)},`,
    `  ${sqlText(resource.resource_type)},`,
    `  ${sqlText(resource.source)},`,
    `  ${sqlText(resource.title)},`,
    `  ${sqlNullableText(resource.organization)},`,
    `  ${sqlNullableText(resource.year_version)},`,
    `  ${sqlText(resource.citation)},`,
    `  ${sqlDate(resource.checked_date)},`,
    `  ${sqlNullableText(resource.reviewer)},`,
    `  ${sqlText(resource.review_status)},`,
    `  ${sqlNullableText(resource.license)},`,
    `  ${sqlTextArray(resource.provenance_tags)}`,
    ')',
    'on conflict (resource_id) do update set',
    '  schema_version = excluded.schema_version,',
    '  resource_type = excluded.resource_type,',
    '  source = excluded.source,',
    '  title = excluded.title,',
    '  organization = excluded.organization,',
    '  year_version = excluded.year_version,',
    '  citation = excluded.citation,',
    '  checked_date = excluded.checked_date,',
    '  reviewer = excluded.reviewer,',
    '  review_status = excluded.review_status,',
    '  license = excluded.license,',
    '  provenance_tags = excluded.provenance_tags;',
    ''
  );
}

lines.push('commit;', '');

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, lines.join('\n'), 'utf8');

console.log(JSON.stringify({
  output: outputPath,
  cases: normalized.length,
  resources: resourceMap.size,
  resource_id_collisions: resourceIdCollisions,
  feature_flag_enabled: false
}));
