-- Viện Thực Hành: owner (2026-10-04) enabled all intake cases for duty. Additive: inserts or activates catalog rows.
insert into y_quan_private.tu_chan_catalog(case_id, room, level, active, track)
select v.case_id, v.room, v.level, true, v.track from (values
  ('noi-tieu-hoa-001','capcuu','Dễ','noi'),
  ('noi-tieu-hoa-002','capcuu','Dễ','noi'),
  ('noi-tieu-hoa-003','capcuu','Trung bình','noi'),
  ('noi-tieu-hoa-004','capcuu','Khó','noi'),
  ('noi-tieu-hoa-005','capcuu','Khó','noi'),
  ('noi-tieu-hoa-006','capcuu','Dễ','noi'),
  ('noi-tieu-hoa-007','capcuu','Trung bình','noi'),
  ('noi-tieu-hoa-008','capcuu','Trung bình','noi'),
  ('noi-tieu-hoa-009','capcuu','Trung bình','noi'),
  ('noi-tieu-hoa-010','capcuu','Khó','noi'),
  ('noi-tim-mach-001','capcuu','Trung bình','noi'),
  ('noi-tim-mach-002','capcuu','Trung bình','noi'),
  ('noi-tim-mach-003','capcuu','Trung bình','noi'),
  ('noi-tim-mach-004','capcuu','Trung bình','noi'),
  ('noi-tim-mach-005','capcuu','Trung bình','noi'),
  ('noi-tim-mach-006','capcuu','Dễ','noi'),
  ('noi-ho-hap-001','capcuu','Trung bình','noi'),
  ('noi-ho-hap-002','capcuu','Khó','noi'),
  ('noi-ho-hap-003','capcuu','Dễ','noi'),
  ('noi-ho-hap-004','capcuu','Khó','noi'),
  ('noi-ho-hap-005','capcuu','Khó','noi'),
  ('noi-noi-tiet-001','capcuu','Khó','noi'),
  ('noi-noi-tiet-002','capcuu','Trung bình','noi'),
  ('noi-than-001','capcuu','Trung bình','noi'),
  ('noi-than-002','capcuu','Khó','noi'),
  ('noi-than-003','capcuu','Dễ','noi'),
  ('noi-than-kinh-001','capcuu','Khó','noi'),
  ('noi-than-kinh-002','capcuu','Trung bình','noi'),
  ('noi-huyet-hoc-001','capcuu','Dễ','noi'),
  ('noi-nhiem-001','capcuu','Trung bình','noi'),
  ('noi-nhiem-002','capcuu','Khó','noi'),
  ('ngoai-bung-001','capcuu','Dễ','ngoai'),
  ('ngoai-bung-002','capcuu','Trung bình','ngoai'),
  ('ngoai-bung-003','capcuu','Trung bình','ngoai'),
  ('ngoai-bung-004','capcuu','Dễ','ngoai'),
  ('ngoai-bung-005','capcuu','Trung bình','ngoai'),
  ('ngoai-bung-006','capcuu','Khó','ngoai'),
  ('ngoai-bung-007','capcuu','Khó','ngoai'),
  ('ngoai-bung-008','capcuu','Dễ','ngoai'),
  ('ngoai-chan-thuong-001','capcuu','Khó','ngoai'),
  ('ngoai-chan-thuong-002','capcuu','Trung bình','ngoai'),
  ('ngoai-chan-thuong-003','capcuu','Dễ','ngoai'),
  ('ngoai-chan-thuong-004','capcuu','Khó','ngoai'),
  ('ngoai-chan-thuong-005','capcuu','Khó','ngoai'),
  ('ngoai-chan-thuong-006','capcuu','Dễ','ngoai'),
  ('ngoai-chan-thuong-007','capcuu','Khó','ngoai'),
  ('ngoai-tiet-nieu-001','capcuu','Trung bình','ngoai'),
  ('ngoai-tiet-nieu-002','capcuu','Trung bình','ngoai'),
  ('ngoai-tiet-nieu-003','capcuu','Khó','ngoai'),
  ('ngoai-vu-001','capcuu','Trung bình','ngoai'),
  ('ngoai-noi-tiet-001','capcuu','Trung bình','ngoai'),
  ('ngoai-mach-001','capcuu','Khó','ngoai'),
  ('ngoai-san-001','capcuu','Trung bình','ngoai'),
  ('noi-cap-cuu-001','capcuu','Khó','noi'),
  ('noi-cap-cuu-002','capcuu','Trung bình','noi'),
  ('noi-cap-cuu-003','capcuu','Trung bình','noi'),
  ('noi-cap-cuu-004','capcuu','Trung bình','noi'),
  ('noi-cap-cuu-005','capcuu','Khó','noi'),
  ('noi-cap-cuu-006','capcuu','Trung bình','noi'),
  ('noi-cap-cuu-007','capcuu','Khó','noi'),
  ('noi-cap-cuu-008','capcuu','Khó','noi'),
  ('noi-cap-cuu-101','capcuu','Trung bình','noi'),
  ('noi-cap-cuu-102','capcuu','Trung bình','noi'),
  ('noi-cap-cuu-103','capcuu','Khó','noi'),
  ('noi-cap-cuu-104','capcuu','Trung bình','noi'),
  ('noi-cap-cuu-105','capcuu','Khó','noi'),
  ('noi-cap-cuu-106','capcuu','Khó','noi'),
  ('noi-cap-cuu-107','capcuu','Khó','noi'),
  ('noi-cap-cuu-108','capcuu','Trung bình','noi'),
  ('ngoai-cap-cuu-001','capcuu','Trung bình','ngoai'),
  ('ngoai-cap-cuu-002','capcuu','Trung bình','ngoai'),
  ('ngoai-cap-cuu-003','capcuu','Khó','ngoai'),
  ('ngoai-cap-cuu-004','capcuu','Trung bình','ngoai'),
  ('ngoai-cap-cuu-005','capcuu','Khó','ngoai'),
  ('ngoai-cap-cuu-006','capcuu','Trung bình','ngoai'),
  ('ngoai-cap-cuu-007','capcuu','Khó','ngoai'),
  ('ngoai-cap-cuu-008','capcuu','Dễ','ngoai'),
  ('ngoai-cap-cuu-101','capcuu','Trung bình','ngoai'),
  ('ngoai-cap-cuu-102','capcuu','Trung bình','ngoai'),
  ('ngoai-cap-cuu-103','capcuu','Khó','ngoai'),
  ('ngoai-cap-cuu-104','capcuu','Trung bình','ngoai'),
  ('ngoai-cap-cuu-105','capcuu','Khó','ngoai'),
  ('ngoai-cap-cuu-106','capcuu','Trung bình','ngoai'),
  ('ngoai-cap-cuu-107','capcuu','Trung bình','ngoai'),
  ('ngoai-cap-cuu-108','capcuu','Khó','ngoai'),
  ('yhct-kham-001','kham','Khó','yhct'),
  ('yhct-kham-002','kham','Khó','yhct'),
  ('yhct-kham-003','kham','Trung bình','yhct'),
  ('yhct-kham-004','kham','Trung bình','yhct'),
  ('yhct-kham-005','kham','Trung bình','yhct'),
  ('yhct-kham-006','kham','Trung bình','yhct'),
  ('yhct-kham-007','kham','Trung bình','yhct'),
  ('yhct-kham-008','kham','Trung bình','yhct'),
  ('yhct-kham-101','kham','Trung bình','yhct'),
  ('yhct-kham-102','kham','Dễ','yhct'),
  ('yhct-kham-103','kham','Trung bình','yhct'),
  ('yhct-kham-104','kham','Trung bình','yhct'),
  ('yhct-kham-105','kham','Trung bình','yhct'),
  ('yhct-kham-106','kham','Khó','yhct'),
  ('yhct-kham-107','kham','Trung bình','yhct'),
  ('yhct-kham-108','kham','Trung bình','yhct')
) as v(case_id, room, level, track)
on conflict (case_id) do update
  set room = excluded.room, level = excluded.level, track = excluded.track, active = true;
